flowchart TD
    A[(2989)] -->|965 antes de 2019| B(2024)
    B --> |15 mal formados| C(2009)
    C --> |339 duplicados | D(1670)
    D --> |1621 1º filtro: TITLE-ABS-KEY | E(49)
    E --> |30 Sem acesso| F(19)
    F --> |2º filtro| G(?)
