---
title: Seleção dos estudos
---
flowchart TD
    A[(2989)] -->|"Anteriores a 2019 (n=123)"| B(2024)
    B --> |"Duplicados (n=339)"| C(1685)
    C --> |"Leitura do título, resumo e palavras-chave (n=1622)"| D(63)
    D --> |"Indisponíveis na íntegra (n=44)"| E(19)
    E --> |"Leitura do conteúdo (n=16)"| F(3)
