flowchart TD
    A[(2989)] -->|965 anteriores a 2019| B(2024)
    B --> |339 duplicados| C(1685)
    C --> |1622 eliminados no 1º filtro: TITLE-ABS-KEY| D(63)
    D --> |44 indisponíveis na íntegra| E(19)
    E --> |16 eliminados no 2º filtro: conteúdo| F(3)
